export const therapists = [
  {
    id: "clara-jensen",
    name: "Clara Jensen",
    role: "Wellness Coordinator",
    rating: 4.9,
    reviews: 186,
    specialty: "Guest care planning",
    image: "https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg",
    imageAlt: "Clara Jensen wellness coordinator",
  },
  {
    id: "maya-thompson",
    name: "Maya Thompson",
    role: "Lead Wellness Therapist",
    rating: 5,
    reviews: 242,
    specialty: "Full-body relaxation",
    image: "https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg",
    imageAlt: "Maya Thompson lead wellness therapist",
  },
  {
    id: "hana-kim",
    name: "Hana Kim",
    role: "Healing Therapist",
    rating: 4.8,
    reviews: 159,
    specialty: "Aromatic therapy",
    image: "https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg",
    imageAlt: "Hana Kim healing therapist",
  },
  {
    id: "elena-cruz",
    name: "Elena Cruz",
    role: "Body Treatment Specialist",
    rating: 4.9,
    reviews: 174,
    specialty: "Body wraps and scrubs",
    image: "https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg",
    imageAlt: "Elena Cruz body treatment specialist",
  },
  {
    id: "nadia-park",
    name: "Nadia Park",
    role: "Facial Care Therapist",
    rating: 4.8,
    reviews: 138,
    specialty: "Facial glow care",
    image: "https://images.pexels.com/photos/5327656/pexels-photo-5327656.jpeg",
    imageAlt: "Nadia Park facial care therapist",
  },
];
