import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { HugeiconsIcon } from "@hugeicons/react";
import { ArrowLeft01Icon, Leaf01Icon } from "@hugeicons/core-free-icons";

const articles: Record<string, { title: string; category: string; date: string; intro: string; sections: { title: string; text: string }[] }> = {
  "massage-and-deep-rest": { title: "How Massage Supports Deep Rest", category: "Massage", date: "May 12, 2026", intro: "Rest is more than simply stopping. Skilled massage helps create the physical conditions that make deeper rest feel possible.", sections: [{ title: "Releasing held tension", text: "Slow, intentional pressure can help tight areas soften while encouraging your attention to return to the body. A comfortable session should feel responsive rather than forced." },{ title: "Creating a quieter rhythm", text: "Steady pacing, warm surroundings, and fewer interruptions give the nervous system time to settle. That sense of quiet can continue after the treatment ends." },{ title: "Carry the calm home", text: "Drink water, avoid rushing into a demanding schedule, and give yourself a gentle evening. Consistent sleep and light movement support the effects of your session." }] },
  "choosing-the-right-facial": { title: "Choosing The Right Facial For Your Skin", category: "Skin care", date: "May 24, 2026", intro: "The most restorative facial begins with what your skin needs today—not with the strongest available treatment.", sections: [{ title: "Start with comfort", text: "Share sensitivity, recent products, and any active irritation with your therapist. Hydration and barrier support are often the best starting points for tired skin." },{ title: "Choose your goal", text: "Glow treatments focus on freshness and hydration, while calming treatments minimize stimulation. Your therapist can adapt timing and products around your needs." },{ title: "Keep aftercare simple", text: "Use gentle cleansing, moisturize, and apply sun protection. Avoid adding several new active products immediately after treatment." }] },
  "wellness-rituals-between-visits": { title: "Small Wellness Rituals Between Visits", category: "Everyday wellness", date: "June 2, 2026", intro: "Restorative care becomes more sustainable when it is supported by small moments of calm throughout the week.", sections: [{ title: "Pause before the rush", text: "Take three unhurried breaths before opening a message, starting work, or moving into your next task." },{ title: "Use warmth intentionally", text: "A warm shower, foot soak, or compress can help ease everyday tension without requiring a long routine." },{ title: "Make rest repeatable", text: "Choose one small practice that fits your life. A consistent ten-minute pause is often more useful than an elaborate ritual you cannot maintain." }] },
  "benefits-of-aromatherapy": { title: "A Gentle Introduction To Aromatherapy", category: "Relaxation", date: "June 18, 2026", intro: "Aromatherapy can add a quiet sensory layer to rest when the scent is chosen with care and used lightly.", sections: [{ title: "Preference comes first", text: "A scent should feel pleasant and subtle. Always mention sensitivities, headaches, pregnancy, or respiratory concerns before an aromatic treatment." },{ title: "Less can be more", text: "A small amount of aroma is enough to shape the atmosphere. Stronger is not necessarily more effective." },{ title: "Pair scent with stillness", text: "Use aroma as a cue to slow breathing, release the shoulders, and create a short transition out of a busy day." }] },
  "prepare-for-your-first-massage": { title: "Preparing For Your First Massage", category: "Spa guide", date: "July 5, 2026", intro: "Your first massage should feel clear, comfortable, and guided from the moment you arrive.", sections: [{ title: "Arrive with time to settle", text: "Coming ten minutes early gives you space to complete a short consultation without feeling rushed." },{ title: "Speak openly", text: "Tell your therapist about injuries, sensitive areas, desired pressure, and anything you prefer to avoid. You can request changes at any point." },{ title: "Wear what feels easy", text: "Comfortable clothing makes arrival and departure simpler. Privacy, towels, and changing time are provided when the treatment requires them." }] },
  "why-consistent-rest-matters": { title: "Why Consistent Rest Matters", category: "Mindful living", date: "July 22, 2026", intro: "The body responds well to rhythms. Regular pauses can make calm more accessible before exhaustion takes over.", sections: [{ title: "Notice early signals", text: "Tight shoulders, shallow breathing, and irritability can be invitations to pause before stress becomes overwhelming." },{ title: "Schedule recovery", text: "Treat rest as a real commitment. A protected hour for movement, massage, or quiet can prevent it from being displaced by less important demands." },{ title: "Build a personal rhythm", text: "Your routine does not need to resemble anyone else’s. Choose a pace and form of care that genuinely fits your energy, schedule, and needs." }] },
};

export function generateStaticParams() { return Object.keys(articles).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const article = articles[(await params).slug]; return article ? { title: article.title, description: article.intro } : {}; }

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const article = articles[(await params).slug]; if (!article) notFound();
  return <article className="px-4 pb-20 pt-32 sm:px-6 lg:px-8 lg:pt-38"><div className="mx-auto max-w-210"><Link href="/blog" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><HugeiconsIcon icon={ArrowLeft01Icon} className="size-4" />Back to journal</Link><div className="mt-8 rounded-3xl bg-secondary px-6 py-10 sm:px-10 sm:py-14"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">{article.category} · {article.date}</p><h1 className="mt-4 text-4xl font-semibold leading-tight sm:text-5xl">{article.title}</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">{article.intro}</p></div><div className="mx-auto max-w-170 py-10">{article.sections.map((section) => <section key={section.title} className="border-b border-border py-7"><div className="flex gap-4"><HugeiconsIcon icon={Leaf01Icon} className="mt-1 size-5 shrink-0 text-primary" /><div><h2 className="text-xl font-semibold">{section.title}</h2><p className="mt-3 text-base leading-8 text-muted-foreground">{section.text}</p></div></div></section>)}<div className="mt-10 rounded-2xl bg-primary p-6 text-primary-foreground"><h2 className="text-xl font-semibold">Ready for a restorative visit?</h2><p className="mt-2 text-sm text-white/70">Choose a treatment and a time that feels comfortable.</p><Link href="/booking" className="mt-5 inline-flex rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-primary">Book an appointment</Link></div></div></div></article>;
}
