"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { HugeiconsIcon } from "@hugeicons/react";
import { CheckmarkCircle02Icon, Mail01Icon, SentIcon } from "@hugeicons/core-free-icons";

export function SupportForm() {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  if (sent) return <div className="rounded-2xl border border-border bg-card p-8 text-center shadow-sm sm:p-10"><div className="mx-auto grid size-14 place-items-center rounded-full bg-accent text-primary"><HugeiconsIcon icon={CheckmarkCircle02Icon} className="size-7" /></div><h2 className="mt-6 text-2xl font-semibold">Your request is ready</h2><p className="mx-auto mt-3 max-w-110 text-sm leading-6 text-muted-foreground">This frontend demo has captured your request. Connect the form to your support service to deliver it to the team.</p><button onClick={() => setSent(false)} className="mt-6 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Send another request</button></div>;
  return <div className="grid overflow-hidden rounded-2xl border border-border bg-card shadow-sm lg:grid-cols-[0.7fr_1.3fr]"><aside className="bg-secondary p-6 sm:p-8"><div className="grid size-11 place-items-center rounded-full bg-background text-primary"><HugeiconsIcon icon={Mail01Icon} className="size-5" /></div><h2 className="mt-6 text-xl font-semibold">Talk with our team</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">For booking changes, vouchers, accessibility needs, or visit questions, send us a note.</p><div className="mt-8 space-y-5 text-sm"><div><p className="font-semibold">Email</p><a href="mailto:hello@chaispa.ph" className="mt-1 block text-muted-foreground">hello@chaispa.ph</a></div><div><p className="font-semibold">Spa hours</p><p className="mt-1 text-muted-foreground">Mon–Fri, 10 AM–9 PM<br />Weekends, 9 AM–8 PM</p></div><Link href="/help" className="inline-flex font-semibold text-primary">Browse common questions</Link></div></aside><form onSubmit={submit} className="grid gap-5 p-6 sm:grid-cols-2 sm:p-8"><label className="text-sm font-semibold">Full name<input required className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 font-normal outline-none focus:border-ring focus:ring-3 focus:ring-ring/15" placeholder="Your full name" /></label><label className="text-sm font-semibold">Email address<input required type="email" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 font-normal outline-none focus:border-ring focus:ring-3 focus:ring-ring/15" placeholder="you@example.com" /></label><label className="text-sm font-semibold sm:col-span-2">What can we help with?<select className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 font-normal outline-none focus:border-ring focus:ring-3 focus:ring-ring/15"><option>Booking or rescheduling</option><option>Payment or refund</option><option>Voucher or loyalty reward</option><option>Membership</option><option>Treatment question</option><option>Other</option></select></label><label className="text-sm font-semibold sm:col-span-2">Message<textarea required className="mt-2 min-h-34 w-full resize-none rounded-xl border border-input bg-background p-3 font-normal outline-none focus:border-ring focus:ring-3 focus:ring-ring/15" placeholder="Tell us how we can help…" /></label><button className="inline-flex h-11 items-center justify-center gap-2 rounded-full bg-primary px-5 text-sm font-semibold text-primary-foreground sm:col-start-2 sm:justify-self-end"><HugeiconsIcon icon={SentIcon} className="size-4" />Send request</button></form></div>;
}
